version: '1'
services:
  backend:
    build: ./backend
    container_name: donezo-backend
    ports:
      - "5000:5000"
    env_file:
      - .env

  frontend:
    build: ./frontend
    container_name: donezo-frontend
    ports:
      - "5174:5173"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app  # Mounts the local frontend folder inside the container
      - /app/node_modules  # Ensures node_modules from the container is used (avoid conflicts)
    environment:
      - CHOKIDAR_USEPOLLING=true  # Enables live reloading for file changes