version: '1'
services:
  backend:
    build: ./backend
    container_name: donezo-backend
    ports:
      - "5000:5000"
    env_file:
      - .env

  frontend:
    build: ./frontend
    container_name: donezo-frontend
    ports:
      - "5174:5173"
    depends_on:
      - backend